### ISSUE TITLE
Add Apache Airfow as a service

### ISSUE THREAD

**Issue by gschmutz** [TrivadisPF/platys#100]
For testing the Amundsen Ingestion it would be good to also have Apache Airflow as a service: <https://hub.docker.com/r/apache/airflow>. 

this is how binami is using it in a `docker-compose.yml` file:

```
  airflow-scheduler:
    image: bitnami/airflow-scheduler:1
    environment:
      - AIRFLOW_DATABASE_NAME=bitnami_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=bitnami1
      - AIRFLOW_EXECUTOR=CeleryExecutor
    volumes:
      - airflow_scheduler_data:/bitnami
  airflow:
    image: bitnami/airflow:1
    environment:
      - AIRFLOW_DATABASE_NAME=bitnami_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=bitnami1
      - AIRFLOW_EXECUTOR=CeleryExecutor
    ports:
      - '8080:8080'
    volumes:
      - airflow_data:/bitnami
```
