### ISSUE TITLE
option --platform-name in init does not work

### ISSUE THREAD

**Issue by gschmutz** [TrivadisPF/platys#109]
Using the option `--platform-name` should change the `platform-name` in the "generated" config.yml, but currently this does not seem to be the case. 

```
 # Default values for the generator
 # this file can be used as a template for a custom configuration
 # or to know about the different variables available for the generator
      platys:
        platform-name: 'default'
        stack-image-name: 'trivadis/platys-modern-data-platform'
        stack-image-version: '1.2.0'
```
