### ISSUE TITLE
Add ulimits clause to StreamSets

### ISSUE THREAD

**Issue by gschmutz** [TrivadisPF/platys#111]
StreamSets on centos needs the following ulimit clause

```
  ulimits:
    nofile:
      soft: 32768
      hard: 32768
```
