### ISSUE TITLE
Move decision on structure to use to `init` phase

### ISSUE THREAD

**Issue by gschmutz** [TrivadisPF/platys#133]
Currently the structure (flat or subfolder) is specified in the gen command. This is a bit error-prone, as when doing a regenerate, you might forget the option you have specified before and both a subfolder and a flat structure might be created in parallel. 

It would be better to specify it in the `init` and store it in the header section at the beginning of the `config.yml` file

```
      platys:
        platform-name: 'printus-platform'
        structure: 'flat'
        stack-image-name: 'trivadis/platys-modern-data-platform'
        stack-image-version: '1.4.0-preview'
```

We should keep the --structure argument in the gen for a while, just checking if it is consistent with the value in the `config.yml` and a message that the setting is deprecated.
