### ISSUE TITLE
Add Presto to Stack

### ISSUE THREAD

**Issue by gschmutz** [TrivadisPF/platys#16]
Add Presto to the stack.

For Presto:

```
  presto-coordinator:
    image: johannestang/prestodb:0.215
    restart: always
    ports:
      - "8080:8080"
    environment:
      S3_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      S3_SECRET_KEY: ${MINIO_SECRET_KEY}
      S3_ENDPOINT: "http://minio:9000"
```

Add Presto to the Hue configuration (checkout <https://github.com/johannestang/bigdata_stack/blob/master/docker-compose.yml>)
