### ISSUE TITLE
--platform-name does not end up in config.yml

### ISSUE THREAD

**Issue by gschmutz** [TrivadisPF/platys#2]
Using the `--platform-name` flag in the `init` does not reflect in `config.yml`

```
      platys:
        platform-name: 'default'
        stack-image-name: 'trivadis/platys-modern-data-platform'
        stack-image-version: '1.5.0'
        structure: 'flat'
```

The name is still on default.
