### ISSUE TITLE
We should change the name of the "config.yml" header properties to reflect correct names

### ISSUE THREAD

**Issue by gschmutz** [TrivadisPF/platys#32]
Currently the header in the `config.yml` holds the following "header" properties. 

```
      platys:
        platform-name: 'default'
        stack-image-name: 'trivadis/platys-modern-data-platform'
        stack-image-version: '1.5.2'
        structure: 'flat'
```

`stack-image-name` and `stack-image-version` are the old names, we have changed them to `platform-stack` and `platform-stack-version` in the documentation and the flags we support. Could we change it to the new names, but still support the old ones in the `platys` CLI (so we are backward compatible to the platform stacks). So we would support both the one above as well as the new shown below:

```
      platys:
        platform-name: 'default'
        platform-stack: 'trivadis/platys-modern-data-platform'
        platform-stack-version: '1.5.2'
        structure: 'flat'
```
