### ISSUE TITLE
After an init and gen I'm getting an error

### ISSUE THREAD

**Issue by gschmutz** [TrivadisPF/platys#34]
When doing an `platys init` followed by a `platys gen` I'm getting an

```
2020/08/07 05:36:43 The config file is not properly formatted or missing information please ensure [platform-name], [stack-image-name] and [stack-image-version] are properly configured
```

error.

Here the head of the `config.yml`

```
      # Default values for the generator
      # this file can be used as a template for a custom configuration
      # or to know about the different variables available for the generator
      platys:
          platform-name: 'platys-demo-platform'
          stack-image-name: 'trivadis/platys-modern-data-platform'
          stack-image-version: '1.6.0'
          structure: 'flat'

```

This is also the case when I'm using an config.yml from the previous version (python CLI).
