### ISSUE TITLE
Wrong values for global configuration after "platys init --enable-services"

### ISSUE THREAD

**Issue by gschmutz** [TrivadisPF/platys#40]
1. I'm doing a `platys init --enable-services KAFKA, PRESTO -w 1.7.0`

2. a config.yml is generated with the following values:

```
      # Default values for the generator
      # this file can be used as a template for a custom configuration
      # or to know about the different variables available for the generator
      platys:
          platform-name: 'default'
          platform-stack: 'trivadis/platys-modern-data-platform'
          platform-stack-version: '1.7.0'
          structure: 'flat'
      # ===== Global configuation, valid for all or a group of services ========
      # Timezone, use a Linux string such as Europe/Zurich or America/New_York
      use_timezone: 'true'
      # the name of the repository to use for private images, which are not on docker hub (currently only Oracle images)
      private_docker_repository_name: 'true'
      # ===== Apache Kafka ========
      KAFKA_enable: true
      
    SPARK_enable: true
      # ===== Apache Hive Metastore ========
      HIVE_METASTORE_enable: true
      # ===== Presto ========
      PRESTO_enable: true
      #=====  MinIO Object Storage ========
      MINIO_enable: true
      AWSCLI_enable: true
```

The value of `use_timezone` and `private_docker_repository_name` are set to `true` which causes the docker-compose.yml to be invalid after a `platys gen`. 

It would be correct to use the values from the "template" `config.yml`.
