### ISSUE TITLE
"platys init" with the "-f" (force) flag does not work correctly

### ISSUE THREAD

**Issue by gschmutz** [TrivadisPF/platys#43]
1. I'm doing a `platys init --enable-services HIVE_METASTORE,MINIO,AWSCLI,PRESTO,PROVISIONING_DATA -s trivadis/platys-modern-data-platform -w 1.8.0-preview`

2. a correct `config.yml` is generated

3. now I'm changing the --enable-services` and use the `-f` flag to force overwriting config.yml: `platys init --enable-services ZOOKEEPER,KAFKA --stack trivadis/platys-modern-data-platform --stack-version 1.7.0   -f

4. the generated `config.yml` is incorrect (from Presto====):

```
      # Default values for the generator
      # this file can be used as a template for a custom configuration
      # or to know about the different variables available for the generator
      platys:
          platform-name: 'default'
          platform-stack: 'trivadis/platys-modern-data-platform'
          platform-stack-version: '1.7.0'
          structure: 'flat'
      # ===== Global configuation, valid for all or a group of services ========
      # Timezone, use a Linux string such as Europe/Zurich or America/New_York
      use_timezone: 'true'
      # the name of the repository to use for private images, which are not on docker hub (currently only Oracle images)
      private_docker_repository_name: 'true'
      # ===== Apache Zookeeper ========
      ZOOKEEPER_enable: true
      # ===== Apache Kafka ========
      KAFKA_enable: true

 Presto ========
      PRESTO_enable: true
      #=====  MinIO Object Storage ========
      MINIO_enable: true
      AWSCLI_enable: true
```
