### ISSUE TITLE
Update kafkadrop image to the obsidiandynamics one

### ISSUE THREAD

**Issue by gschmutz** [TrivadisPF/platys#81]
Use the following service definition

```
  kafdrop:
    image: obsidiandynamics/kafdrop
    restart: "no"
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:29092"
      JVM_OPTS: "-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
    depends_on:
      - "kafka"
```
